#! bin/bash

#installing init system and driver-related packages
apt-get install --no-install-recommends \
systemd \
systemd-sysv \
libpam-systemd \
libsystemd0 \
dialog \
linux-image-amd64 \
firmware-linux \
firmware-intel-sound \
firmware-iwlwifi \
firmware-realtek \
intel-microcode \
i965-va-driver \
acpi-support -y

#installing other essential package (network etc)
apt-get install --no-install-recommends \
dhcpcd5 \
iwd \
iproute2 \
iputils-ping \
grub-efi \
efibootmgr \
os-prober \
nano \
doas \
zsh -y
