#!/bin/bash

#check your fstab
cat /etc/fstab

#set your hostname
echo "masterbox" > /etc/hostname

#set your localhost or shit (i don't understand)
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 masterbox.localdomain masterbox" >> /etc/hosts

#set other things
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc
sed -i '165s/.//' /etc/locale.gen #this should be en_US one
sed -i '280s/.//' /etc/locale.gen #this one should be id_ID. you can remove this
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

#configure sourcelist
echo -e "deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list

#updating sourcelist
apt update

#installing package
#installing init system and driver-related (intel) packages
apt-get install --no-install-recommends \
systemd \
systemd-sysv \
libpam-systemd \
libsystemd0 \
dialog \
linux-image-amd64 \
firmware-linux \
firmware-intel-sound \
firmware-iwlwifi \
firmware-realtek \
intel-microcode \
i965-va-driver \
acpi-support -y

#installing other essential package (network etc)
apt-get install --no-install-recommends \
dhcpcd5 \
iwd \
iproute2 \
iputils-ping \
grub-efi \
efibootmgr \
os-prober \
nano -y

#installing grub
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Debian #change the directory to /boot/efi is you mounted the EFI partition at /boot/efi
update-grub

#create user
useradd -m aria
usermod -aG video,audio aria

#create password for root and user
echo "password root"
passwd
echo "password user"
passwd aria

#managing su privileges (sudo)
#apt install sudo
#adduser (username) sudo

#managing su privileges (doas and resurrecting the wheel group)
apt install doas
sed -i '15s/.//' /etc/pam.d/su #resurrecting the wheel group, baby
addgroup --system wheel #adding wheel group
adduser aria wheel
echo "permit :wheel as root" > /etc/doas.conf #configuring doas
chown -c root:root /etc/doas.conf
chmod -c 0400 /etc/doas.conf
ln -s /usr/bin/doas /usr/bin/sudo #linking doas to sudo just in case

#cleanup
rm debootstrap-chroot

echo "check fstab, and edit the swap part if you use swapfile (you don't need any fancy compression or other option like the other subvol). \
also remove subvolid option from the fstab, to make it easier if you need to manually rollback (the arch linux way)"
